# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: werk-envio-indexer
description: Indexer for the Werk Station Registry and Space contracts
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "value"
# Global contract definitions that must contain all definitions except
# addresses. We can share a single handler/abi/event definitions
# for contracts across multiple chains
contracts:
  - name: StationRegistry
    handler: src/station-registry/index.ts
    events:
      - event: SpaceCreated(address indexed owner, uint256 indexed stationId, address space)
      - event: ModuleKeeperUpdated(address newModuleKeeper)
      - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
      - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
      - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
      - event: SignerAdded(address indexed account, address indexed signer)
      - event: SignerRemoved(address indexed account, address indexed signer)
      - event: StationOwnershipTransferred(uint256 indexed stationId, address oldOwner, address newOwner)
  - name: Space
    handler: src/space/index.ts
    events:
      - event: NativeReceived(address indexed from, uint256 amount)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
networks:
  - id: 84532 # Base Sepolia
    start_block: 25689188
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x05880666779aeE8ff9492740c64cc83268C1B8FC
      - name: Space # A reference to the global Space contract definition
  - id: 11155111 # Ethereum Sepolia
    start_block: 8318596
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x05880666779aeE8ff9492740c64cc83268C1B8FC
      - name: Space # A reference to the global Space contract definition
