# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: werk-envio-indexer
description: Indexer for the Werk Station Registry and Space contracts
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "value"
# Global contract definitions that must contain all definitions except
# addresses. We can share a single handler/abi/event definitions
# for contracts across multiple chains
contracts:
  - name: StationRegistry
    handler: src/station-registry/index.ts
    events:
      - event: SpaceCreated(address indexed admin, address space)
      - event: ModuleKeeperUpdated(address newModuleKeeper)
      - event: SignerAdded(address indexed account, address indexed signer)
      - event: SignerRemoved(address indexed account, address indexed signer)
  - name: Space
    handler: src/space/index.ts
    events:
      - event: NativeReceived(address indexed from, uint256 amount)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
      - event: AssetWithdrawn(address indexed to, address indexed asset, uint256 amount)
unordered_multichain_mode: true
networks:
  - id: 8453 # Base
    start_block: 0 # With HyperSync, you can use 0 regardless of contract deployment time
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x2A1F9a6e093Eee27B883f5B473a1f190010151a9
      - name: Space # A reference to the global Space contract definition
  - id: 1 # Ethereum
    start_block: 0 # With HyperSync, you can use 0 regardless of contract deployment time
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x2A1F9a6e093Eee27B883f5B473a1f190010151a9
      - name: Space # A reference to the global Space contract definition
  - id: 84532 # Base Sepolia
    start_block: 0 # With HyperSync, you can use 0 regardless of contract deployment time
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x2A1F9a6e093Eee27B883f5B473a1f190010151a9
      - name: Space # A reference to the global Space contract definition
  - id: 11155111 # Ethereum Sepolia
    start_block: 0 # With HyperSync, you can use 0 regardless of contract deployment time
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x2A1F9a6e093Eee27B883f5B473a1f190010151a9
      - name: Space # A reference to the global Space contract definition
  - id: 999 # HyperEVM
    start_block: 0 # With HyperSync, you can use 0 regardless of contract deployment time
    contracts:
      - name: StationRegistry # A reference to the global StationRegistry contract definition
        address:
          - 0x2A1F9a6e093Eee27B883f5B473a1f190010151a9
      - name: Space # A reference to the global Space contract definition
