# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
  - name: StationRegistry
    handler: src/EventHandlers.ts
    events:
      - event: AccountCreated(address indexed account, address indexed accountAdmin)
      - event: ModuleKeeperUpdated(address newModuleKeeper)
      - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
      - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
      - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
      - event: SignerAdded(address indexed account, address indexed signer)
      - event: SignerRemoved(address indexed account, address indexed signer)
      - event: SpaceCreated(address indexed owner, uint256 indexed stationId, address space)
      - event: StationOwnershipTransferred(uint256 indexed stationId, address oldOwner, address newOwner)
networks:
  - id: 84532
    start_block: 0
    contracts:
      - name: StationRegistry
        address:
          - 0xe1026Ab8272746dc93Efcd1423355F3b23E3e0aB
  - id: 11155111
    start_block: 0
    contracts:
      - name: StationRegistry
        address:
          - 0xe1026Ab8272746dc93Efcd1423355F3b23E3e0aB
