type Space_Transfer {
  id: ID!
  timestamp: BigInt!
  chainId: String!
  asset: String!
  from: String!
  to: String!
  value: String!
  hash: Bytes!
}

type StationRegistry_ModuleKeeperUpdated {
  id: ID!
  newModuleKeeper: String!
}

type StationRegistry_SignerAdded {
  id: ID!
  account: String!
  signer: String!
}

type StationRegistry_SignerRemoved {
  id: ID!
  account: String!
  signer: String!
}

type StationRegistry_Spaces {
  id: ID!
  chainId: String!
  spaces: [String!]!
}

type StationRegistry_SpaceCreated {
  id: ID!
  admin: String!
  space: String!
}

